xlsx_urls:
  - "https://schedule-cloud.cfuv.ru/index.php/s/YLoTDF3GqDjnDbR/download/09.03.01%20Информатика%20и%20вычислительная%20техника,09.03.04%20Программная%20инженерия%20%281-4%29.xlsx"

study_start_date: 2024-09-02
lesson_start_time: 8:00:00
lesson_length: 1:30:00
breaks:
  - 20:00
  - 10:00
  - 20:00
  - 10:00
  - 10:00
  - 10:00
  - 10:00
